version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: cobooking-postgres
    environment:
      POSTGRES_DB: cobooking_db
      POSTGRES_PASSWORD: cobooking2025
      POSTGRES_USER: cobooking
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: cobooking-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
